# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Ice Cream Club
email: dirtyboots9501@gmail.com
description: "아이스크림 개발자"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dirtyboots95.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: "dirtyboots95"
keywords: ["개발", "프로그래밍", "독서", "영화", "리뷰", "블로그", "기술"]
#twitter_username: jekyllrb
#github_username:  jekyll

# SEO Settings
google_site_verification: "google-site-verification=h8-gRgipLXTKv4m7h7n1fVAji9jWYSJJSSQFnGDk68I" # Google Search Console verification code
naver_site_verification: "" # Naver Search Advisor verification code
favicon: "/assets/images/favicon.png"

# permalink: /:collection/:slug.html

# Build settings
theme: no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<-" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  empty_posts_message: "No posts yet." # message shown when no posts exist
#  lowercase_titles: true # show titles in lowercase in lists

# Comments provider
disqus_shortname: dirtyboots95

# Web Analytics Settings
analytics:
  google:
    id: "G-H9LCES4944" # Google Analytics 4 Measurement ID
    property_id: "503083435" # GA4 Property ID (실제 속성 ID)
    stream_id: "12092786575" # GA4 Stream ID
    account: "dirtyboots95" # GA4 계정명
  goatcounter:
    id: "dirtyboots95"
  plausible:
    domain: "dirtyboots95.github.io" # Plausible Analytics 도메인
goat_counter: "dirtyboots95"

# Page views settings
pageviews:
  provider: goatcounter # now only supports 'goatcounter'

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Sitemap settings
sitemap:
  exclude: ["/draft/", "/404.html"]
  include: ["/journal/", "/book/", "/movie/", "/gallery/"]
  priority: 0.8
  changefreq: "monthly"

# Collections
collections:
  journal:
    output: true
    permalink: /journal/:slug.html
  book:
    output: true
    permalink: /book/:slug.html
  movie:
    output: true
    permalink: /movie/:slug.html
  gallery:
    output: true
    permalink: /gallery/:slug.html

#jektex:
#  cache_dir: ".jektex-cache"
#  ignore: ["*.xml"]
#  silent: false
#  macros:
#    - ["\\Q", "\\mathbb{Q}"]
#    - ["\\C", "\\mathbb{C}"]

# Jekyll Admin 설정
# 옵션 1: 개발 환경에서만 활성화 (기본값 - 가장 안전)
# 옵션 2: 프로덕션에서도 활성화 (추가 보안 설정 필요)
{% if jekyll.environment == "development" %}
jekyll_admin:
  hidden_links:
    - datafiles
    - configuration
  homepage: "posts"
  # 보안 설정
  whitelist: []  # 개발 환경: 모든 IP 허용
  # 파일 업로드 설정
  static_files:
    upload_dir: "assets/images"
{% else %}
# 프로덕션 환경에서도 Admin 사용하려면 아래 주석 해제
# 주의: 추가 보안 설정(기본 인증, IP 제한 등)이 필요합니다!
# jekyll_admin:
#   hidden_links:
#     - datafiles
#     - configuration
#   homepage: "posts"
#   # 보안 설정 - 특정 IP만 허용
#   whitelist: ["127.0.0.1", "::1", "YOUR_IP_ADDRESS"]
#   static_files:
#     upload_dir: "assets/images"
  # 컬렉션별 설정
  collections:
    journal:
      # 제목을 파일명으로 자동 변환하는 규칙 (Makefile과 동일)
      # 1. 한글, 영문, 숫자, 공백, 하이픈만 허용
      # 2. 공백을 하이픈으로 변환
      # 3. 연속된 하이픈을 하나로 변환
      # 4. 앞뒤 하이픈 제거
      slug: "{{ title | slugify: 'default' | replace: ' ', '-' | replace: '--', '-' | replace: '---', '-' | replace: '----', '-' }}"
    book:
      # 제목을 파일명으로 자동 변환하는 규칙 (Makefile과 동일)
      slug: "{{ title | slugify: 'default' | replace: ' ', '-' | replace: '--', '-' | replace: '---', '-' | replace: '----', '-' }}"
    movie:
      # 제목을 파일명으로 자동 변환하는 규칙 (Makefile과 동일)
      slug: "{{ title | slugify: 'default' | replace: ' ', '-' | replace: '--', '-' | replace: '---', '-' | replace: '----', '-' }}"
{% endif %}