# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Ice Cream Club
email: dirtyboots9501@gmail.com
description: "아이스크림 개발자"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dirtyboots95.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

permalink: /:slug.html

# Build settings
theme: no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "<-" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  empty_posts_message: "아직 등록된 글이 없습니다." # message shown when no posts exist
#  lowercase_titles: true # show titles in lowercase in lists

# Comments provider
disqus_shortname: dirtyboots95

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  gallery:
    output: true
    permalink: /gallery/:slug.html

#jektex:
#  cache_dir: ".jektex-cache"
#  ignore: ["*.xml"]
#  silent: false
#  macros:
#    - ["\\Q", "\\mathbb{Q}"]
#    - ["\\C", "\\mathbb{C}"]