backend:
  name: test-repo

# Media storage configuration
media_folder: "assets/images" # Media files will be stored in the repo under assets/images
public_folder: "/assets/images" # The src attribute for uploaded media will begin with /assets/images

# Site URL (optional, used for preview links in the CMS)
site_url: http://localhost:4000
display_url: http://localhost:4000

# Collections configuration
collections:
  # Journal posts collection
  - name: "journal"
    label: "일기"
    folder: "_posts/journal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "카테고리", name: "categories", widget: "list", default: ["journal"]}
      - {label: "태그", name: "tags", widget: "list"}
      - {label: "내용", name: "body", widget: "markdown"}
      - {label: "이미지", name: "image", widget: "image", required: false}

  # Book reviews collection
  - name: "book"
    label: "독서"
    folder: "_posts/book"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "카테고리", name: "categories", widget: "list", default: ["book"]}
      - {label: "태그", name: "tags", widget: "list"}
      - {label: "내용", name: "body", widget: "markdown"}
      - {label: "책 표지", name: "book_cover", widget: "image", required: false}
      - {label: "저자", name: "author", widget: "string", required: false}
      - {label: "출판사", name: "publisher", widget: "string", required: false}
      - {label: "출간일", name: "published_date", widget: "date", required: false}
      - {label: "평점", name: "rating", widget: "number", min: 1, max: 5, step: 0.5, required: false}

  # Movie reviews collection
  - name: "movie"
    label: "영화"
    folder: "_posts/movie"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "카테고리", name: "categories", widget: "list", default: ["movie"]}
      - {label: "태그", name: "tags", widget: "list"}
      - {label: "내용", name: "body", widget: "markdown"}
      - {label: "포스터", name: "poster", widget: "image", required: false}
      - {label: "감독", name: "director", widget: "string", required: false}
      - {label: "출연진", name: "cast", widget: "list", required: false}
      - {label: "개봉일", name: "release_date", widget: "date", required: false}
      - {label: "평점", name: "rating", widget: "number", min: 1, max: 5, step: 0.5, required: false}

  # Gallery collection
  - name: "gallery"
    label: "갤러리"
    folder: "_gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "이미지", name: "image", widget: "image"}
      - {label: "설명", name: "description", widget: "text", required: false}
      - {label: "태그", name: "tags", widget: "list", required: false}

  # Draft posts collection
  - name: "draft"
    label: "초안"
    folder: "_posts/draft"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "날짜", name: "date", widget: "datetime"}
      - {label: "카테고리", name: "categories", widget: "list", default: ["draft"]}
      - {label: "태그", name: "tags", widget: "list"}
      - {label: "내용", name: "body", widget: "markdown"}
      - {label: "이미지", name: "image", widget: "image", required: false}

# Global settings
publish_mode: editorial_workflow
